#
# Common make rules for all subfolders.
#
# Author: Per Lundberg <per@halleluja.nu>
# Copyright: © 2008-2009, 2013 Per Lundberg
#

UNAME := $(shell uname)

ifeq ($(UNAME),Darwin)
CC=/usr/local/gcc-4.7.2-for-linux64/bin/x86_64-pc-linux-gcc
TARGET_PATH=/Volumes/cocOS
endif
