#
# Common make rules for all subfolders.
#
# Author: Per Lundberg <per@halleluja.nu>
# Copyright: © 2013 Per Lundberg
#

UNAME := $(shell uname)

ifeq ($(UNAME),Darwin)
CC=/usr/local/gcc-4.7.2-for-linux64/bin/x86_64-pc-linux-gcc
TARGET_PATH=/Volumes/cocOS
GCC_INCLUDES=-I/usr/local/gcc-4.7.2-for-linux64/lib/gcc/x86_64-pc-linux/4.7.2/include/
endif

CFLAGS = $(AS_FLAGS) --std=gnu99 -ggdb -nostdinc $(GCC_INCLUDES) -I..
